www/nginx: Log display improvements
opnsense/plugins pull request #2165
Opened 2020-12-31 00:18 UTC by 8191

Shift complete log display logic from client to server to allow efficient display of big logfiles.

2021-01-06 09:09 UTC, 8191 commented
@fabianfrz Could you please have a look at this rather big PR? I think it needs some more work as the other open PRs might conflict with some files here, but the functionality itself is ready for review/commenting. Thanks!

2021-01-06 14:45 UTC, 8191 commented on www/nginx/src/opnsense/mvc/app/library/OPNsense/Nginx/LogParserBase.php
> +            for ($line = '', $pos = -2; fseek($handle, $pos, SEEK_END) !== -1; $pos--) {
The PHP implementation of `SEEK_END` seems to slow the file reading dramatically (approx. 600ms vs. 70ms when reading the complete file linear).
As one nginx log file typically is not huge in size, maybe reading the complete file to memory is fine as well.

2021-01-06 22:15 UTC, 8191 commented on www/nginx/src/opnsense/mvc/app/library/OPNsense/Nginx/LogParserBase.php
> +
add `unset($lines)` to free memory of potential big logfile

2021-02-21 22:08 UTC, fabianfrz requested changes
my fault, I never published the review :(

2021-12-03 21:33 UTC, 8191 commented on www/nginx/src/opnsense/www/js/nginx/src/controller/LogView.js
> +        let tbody = this.$('tbody');
@fabianfrz Actually if I read the Backbone docs correctly, `$` does the same here:

> If jQuery is included on the page, each view has a $ function that runs queries scoped within the view's element.

_Source: https://backbonejs.org/#View-dollar_

2021-12-03 21:36 UTC, 8191 commented on www/nginx/src/opnsense/www/js/nginx/src/controller/LogView.js
> +            this.$('#resultcount').html(this.collection.displayed_entries);
If my assumption above is correct, then this should also find the HTML elements by ID _within_ the view...

2021-12-03 21:51 UTC, 8191 commented on www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/LogsController.php
> +        // TODO check $fileno
I've removed that comment as this case is actually handles within the configd script (it's easier there, as here in the web-frontend we do not have FS access).

2021-12-03 22:26 UTC, 8191 commented on www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/LogsController.php
> +        return $this->sendConfigdToClient("nginx log $type $uuid $fileno $page $perPage $query");
Thanks! Nice catch!
I've encoded the complete query in base64 to fix that.

2021-12-07 21:05 UTC, fabianfrz commented on www/nginx/src/opnsense/www/js/nginx/src/controller/LogView.js
> +        let tbody = this.$('tbody');
Ok, I thought about $el, but sure you are right.

2021-12-07 21:06 UTC, fabianfrz approved these changes

2021-12-08 11:45 UTC, fichtner approved these changes
looks ok, @fabianfrz will you merge or shall I?

2021-12-09 07:58 UTC, 8191 commented
I've updated the release notes (b80234f) - added the change to 1.24 as it seems still not released.

2021-12-09 08:03 UTC, fichtner commented
1.24 is out so we need 1.25 for this https://github.com/opnsense/changelog/blob/9f38b6d268a06558b2eea3efe8196ab217866d71/community/21.7/21.7.6#L34 :)

2021-12-09 12:03 UTC, 8191 commented
@fichtner Oh! Thanks to point that out. Changed the release notes in 1d82b91.

2021-12-09 12:06 UTC, 8191 commented
@fichtner Oh! Thanks to point that out! I've updated the release notes and plugin version (c9c7362).

2021-12-09 12:07 UTC, fichtner commented on www/nginx/pkg-descr
> +1.25
```suggestion
1.25

```

2021-12-09 12:08 UTC, merged

2021-12-09 12:08 UTC, fichtner commented
Merged, thanks!

2021-12-09 13:23 UTC, kulikov-a commented
Thanks a lot to all. looks great!