Replace stop action by the reload option in reconfigureForceRestart
opnsense/plugins pull request #2450
Opened 2021-07-07 07:49 UTC by Neozlag

It seems that the reload option is better than the stop option, because stop action stop WebRTC communication. I have configured the reload option in another pull request.

2021-07-07 08:29 UTC, fichtner requested changes
Speaking operationally this makes no sense. If we disable nginx and want it to stop we cannot reload it here...

2021-07-07 09:44 UTC, Neozlag commented
I seem to have misunderstood something. Why when the user clicks on the orange button to reload the web server configuration, the action reconfigureForceRestart is launched? Isn't it better not to stop nginx, but just reload it?

2021-07-07 09:45 UTC, fichtner commented
It's also executed when you enable or disable nginx and hit apply.

2021-07-07 09:59 UTC, Neozlag commented
Okay, I didn't know that. So it needed to separate the apply button than the reload, right ?

2021-07-07 10:02 UTC, fichtner commented
For one the code should not implement reconfigureAction() at all since it is outdated code and the default is likely much better. Secondly, reconfigureForceRestart() needs to be implemented as { return 0; } to avoid the stop on a reconfigure to reach the actual reload below...

2021-07-07 13:10 UTC, Neozlag commented
So, if we had    
protected function reconfigureForceRestart()
    {
        return 0;
    }
It should be good ?

2021-07-07 13:12 UTC, fichtner commented
And reconfigureAction() removed, yes

2021-07-07 13:23 UTC, Neozlag commented
Okay Thank you, I have tried it, and it seems to be good and just reload the configuration :).
Did I create a pull request for that ?
And I have a last question, when I delete reconfigureAction in Nginx ServiceController.php file, I use the default, in which file is the default reconfigureAction ?

2021-07-07 13:32 UTC, fichtner commented
Yes, the default comes from core:

https://github.com/opnsense/core/blob/b74b3799db80247c50524e066e0747c1c0f5d783/src/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableServiceControllerBase.php#L161-L167

Can you create a full PR with the required action added as well?

2021-07-07 14:04 UTC, Neozlag commented
Okay, normally I did it properly.
Thank you for you help :).

2021-07-07 18:01 UTC, fichtner commented on www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/ServiceController.php
> +
```suggestion
    protected function reconfigureForceRestart() {
        return 0;
    }
```

2021-07-07 18:02 UTC, fichtner commented on www/nginx/src/opnsense/service/conf/actions.d/actions_nginx.conf
> +command:/usr/local/etc/rc.d/nginx reload;exit 0
```suggestion
command:/usr/local/etc/rc.d/nginx reload
```

2021-07-07 18:03 UTC, fichtner approved these changes
Looks good to me, will test and merge tomorrow.

2021-07-29 09:29 UTC, Neozlag commented
Hello, it seems after the upgrade to 21.1.9 version, it's good, but after upgrade to 21.7, it rollbacks to the old configuration of the nginx plugin ...

2021-07-29 12:39 UTC, fichtner commented
I forgot about this, sorry. 21.7 upgrade reinstalls all plugins cleanly so you have to apply your code again. 21.7.1 will have this code most likely.


Cheers,
Franco

2021-07-29 12:39 UTC, merged

2021-07-29 12:39 UTC, fichtner commented
Thanks!

2021-11-15 10:20 UTC, Neozlag commented
Hello, I had just upgrade an Opnsense to the 21.7.4 version, but it rollbacks to the old configuration of the nginx plugin ...