FTP backup plugin
opnsense/plugins pull request #2473
Opened 2021-07-24 13:02 UTC by manhofmann

2021-12-06 20:12 UTC, manhofmann commented
Hello @fraenki 
any chance to look into this pull request?
Best regards
Manuel

2021-12-07 10:18 UTC, fraenki commented
@manhofmann sorry, not my area of expertise :)

2022-01-03 22:11 UTC, fabianfrz requested changes
I added some comments of some things I have seen.

Additionally, FTP servers in contrast to Nextcloud, do not necessary have an automatically handled file retention (if configured). This means that you may implement a file rotation system like in the Google Drive backup if you like.

2022-01-03 22:11 UTC, fabianfrz commented on sysutils/ftp-backup/src/opnsense/mvc/app/library/OPNsense/Backup/FTP.php
> +            CURLOPT_USERPWD => $username . ":" . $password,
There seems to be another interesting option worth to try:
CURLOPT_FTP_CREATE_MISSING_DIRS

2022-01-03 22:11 UTC, fabianfrz commented on sysutils/ftp-backup/pkg-descr
> +strongly advise to not use a public service to send backups to.
I would also mention the optional usage of TLS (at least on the data connection).

2022-06-29 12:29 UTC, AdSchellevis commented
no feedback

2022-06-29 12:29 UTC, closed without merging