Update Nextcloud.php
opnsense/plugins pull request #2662
Opened 2021-11-22 17:14 UTC by Neozlag

It seems the try in the getInternalUsername function was not placed very well, so the throw exception in the ocs_request function didn't work.

2022-01-03 22:05 UTC, fabianfrz requested changes

2022-01-03 22:05 UTC, fabianfrz commented on sysutils/nextcloud-backup/src/opnsense/mvc/app/library/OPNsense/Backup/Nextcloud.php
> +        try {
you you move that, you have to fix the indention as well.

2022-01-04 08:27 UTC, Neozlag reviewed
Oh yes, sorry, I was just copying and pasting.

2022-01-25 09:15 UTC, merged

2022-01-25 09:15 UTC, fichtner commented
merged, thanks!

2022-01-25 09:15 UTC, Neozlag reviewed
Now it's normally well indented, I'm sorry for this mistake, I am not a developer ^^.
Regards,