Added Simply.com (used to be UnoEuro). There is an open PR in acme.sh…
opnsense/plugins pull request #2888
Opened 2022-03-10 10:21 UTC by nikolajbrinch

… DEV branch #3978, that fixes dns for simply, since they removed support for the old UnoEuro REST API (V1) in favour of V2 that uses Basic Auth.

The current dns_simply.sh does not work, neither does dns_unoeuro.sh in acme.sh, when the PR in acme.sh is merged it will work.
There is no danger in merging this, since it will just not work, just like the UnoEuro doesn't work. But when acme.sh merges PR #3978, it will start working.

2022-03-13 21:34 UTC, fraenki requested changes

2022-03-13 21:34 UTC, fraenki commented on security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsSimply.php
> + * Copyright (C) 2020 Frank Wall
Please adjust the copyright, the current year and your name is expected here.

2022-03-13 21:36 UTC, fraenki commented
This will be merged when the following conditions are met:

* https://github.com/acmesh-official/acme.sh/pull/3978 is merged upstream
* https://github.com/acmesh-official/acme.sh/pull/3978 is part of an [official release](https://github.com/acmesh-official/acme.sh/releases) of acme.sh

In the past I've merged similar PRs too soon, which caused confusion and frustration for users.

2022-04-05 23:12 UTC, leifnel commented
The simply v2 plugins from upstream works, except it doesn't delete the txt-records after use.

2022-07-27 12:54 UTC, merged

2022-07-27 12:54 UTC, fraenki commented
Merged, thanks!