Correct TransIP API
opnsense/plugins pull request #2932
Opened 2022-04-08 10:21 UTC by MeganerdNL

API key field  type of Transip corrected from "text" to "textbox". It was nog working with "text" due to linebreaks. I tested and this and now it works. Furthernore added a note that 300s sleep time is recommended.

2022-04-08 11:00 UTC, MeganerdNL commented
This solves #2924

2022-04-13 13:24 UTC, fraenki commented on security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
> +        <style>table_dns table_dns_transip</style>
I think this `<style>` tag can be omitted, because the previous tag already added it.

2022-04-13 13:26 UTC, fraenki requested changes
Please remove the duplicated style tag, I'll merge it afterwards.

2022-04-16 09:13 UTC, MeganerdNL commented
I am very happy to do that, but in in the same file there are more like this (Vultr, Linode, Namesilo). Are you sure this is neccessary and are the other double <style> ones also wrong then?

2022-05-01 15:30 UTC, fraenki approved these changes
Thanks for taking care of this.

2022-05-01 15:31 UTC, merged