Increase default timeout from 10 seconds to 30 seconds. Closes #3051 and Possibly #3017
opnsense/plugins pull request #3133
Opened 2022-09-21 15:25 UTC by ilikenwf

This simple change bumps the timeout for fetching our own IP address to 30 seconds instead of 10, as updating the Dynamic IP is not super time sensitive when it comes to this minor adjustment.

In my testing, and in others in #3051 we have determined the timeout to be a major cause of issues for those of us with higher latency than some connections.

2022-09-21 15:27 UTC, fichtner requested changes
The timeout was introduced to keep some pages from hanging without proper SSL support. I see no evidence of why this timeout matters other than that it "fixes" the page load. I do not want to go forward without the reason for the long page load for a couple of bytes and a header.

2022-09-21 15:32 UTC, ilikenwf commented
> The timeout was introduced to keep some pages from hanging without proper SSL support. I see no evidence of why this timeout matters other than that it "fixes" the page load. I do not want to go forward without the reason for the long page load for a couple of bytes and a header.

In my particular case, it is because I use a cellular internet provider as I live in a remote location. As such, my latency is higher, so it sometimes takes a few more seconds to resolve, request, and read a response than it would if I were on a fiber connection.

2022-09-21 22:05 UTC, christian-schulze commented
@ilikenwf in my case, DNS requests take **_much_** longer when they originate from the opnsense device, if the requests come from any other device on the network they are fast.
For my set up I use a pihole which forwards traffic to unbound on a custom port, all devices on the network are configured to use the pihole directly. I also have a NAT rule which forwards port 53 back to the pihole if any device tries to query opnsense directly for DNS, I suspect this port forward is somehow related. Disabling the rule does not fix the issue however, so at this stage the only way I've been able to get the ddclient plugin to work is increasing the hard coded timeout.

I think an appropriate solution is to expose the timeout in the web UI, with the default remaining as is. That way the timeout remains as is, but corner cases like ours can be addressed.

@fichtner I am happy to work on this if you agree to the feature request.

2022-09-22 06:46 UTC, AdSchellevis commented
@christian-schulze a configurable timeout defaulting to the current 10 seconds sounds reasonable to me, if you open a PR, I'll take a look.

2022-09-22 06:56 UTC, ilikenwf commented
With that, I'll leave it to @christian-schulze . Closing.

2022-09-22 06:56 UTC, closed without merging